# Generated by Django 4.0.2 on 2022-02-12 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do tipo de categoria do produto', max_length=20)),
                ('percentage_cashback', models.FloatField(default=5, help_text='Porcentagem do cashback (PS: de 0 a 100%)')),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('qty', models.IntegerField()),
                ('type', models.ForeignKey(blank=True, help_text='Tipo da categoria dos produtos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashback.type')),
            ],
        ),
    ]
