# Generated by Django 4.0.2 on 2022-02-12 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_type_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0, help_text='Total da minha compra')),
                ('sold_at', models.DateTimeField(help_text='Data que aconteceu a compra', verbose_name='data de venda')),
                ('customer', models.ForeignKey(help_text='Customer que fez essa compra', on_delete=django.db.models.deletion.CASCADE, to='cashback.customer')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashback.purchase'),
        ),
    ]
